### ISSUE TITLE
No such device

### ISSUE THREAD

**Issue by zjcboy** [Macr0phag3/Sniffer#2]
![image](https://user-images.githubusercontent.com/8294751/44667014-47953f80-aa4c-11e8-8fdc-16bc9d1dcf0a.png)

请问怎么解决这个问题？

**Comment by Macr0phag3** [comment]
你是不是自己指定了网卡的名字？如果是的话，它的意思是不存在这个网卡。若不是，贴出完整的命令我看看 @zjcboy

**Comment by zjcboy** [comment]
@Macr0phag3 你好，我没有指定网卡，请看下图，方便的话可以加下我的，希望能与你学习和探讨。
![image](https://user-images.githubusercontent.com/8294751/44669171-c771d880-aa51-11e8-8a06-b5d1546a4295.png)
![image](https://user-images.githubusercontent.com/8294751/44669200-d3f63100-aa51-11e8-8ced-be0ac8a6e8cc.png)

**Comment by minliacom** [comment]
我也要学习一下，在Docker跑起来，方便的话加下QQ：471594018 谢谢作者大大

**Comment by Macr0phag3** [comment]
@minliacom 有问题先提一下 issue，如果解决不了我再加你。这样能帮助后面来的人

**Comment by Macr0phag3** [comment]
本 issue 已经解决。
问题一：**no such device**。原因是 zjcboy 不小心改动了源码。
问题二：无法获得网卡的 ip。获得网卡 ip 的方式为 ifconfig 后进行正则，可以在源码中写死 ip，或者自己修正一下正则。源码位置为：**Sniffer/Sniffer v3.0/Toolbox/IfaceTools.py**
